"""create_exceptions_table

Revision ID: 1760583762
Revises: abc123def456
Create Date: 2025-10-16 03:02:42.540659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1760583762'
down_revision: Union[str, None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'exceptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dataset_id', sa.Integer(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('row_ptr', sa.String(), nullable=False),
        sa.Column('error_code', sa.String(), nullable=False),
        sa.Column('hint', sa.String(), nullable=False),
        sa.Column('offending', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_created_at'), 'exceptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_exceptions_error_code'), 'exceptions', ['error_code'], unique=False)
    op.create_index(op.f('ix_exceptions_model'), 'exceptions', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_model'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_error_code'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_created_at'), table_name='exceptions')
    op.drop_table('exceptions')
    # ### end Alembic commands ###
