"""add_vocab_policy_tables

Revision ID: 29d0cfa904f6
Revises: 87de087c7195
Create Date: 2025-10-24 15:35:52.820151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d0cfa904f6'
down_revision: Union[str, None] = '87de087c7195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('canonical_value', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_alias_lookup', 'vocab_aliases', ['model', 'field', 'alias', 'company_id'], unique=True)
    op.create_index(op.f('ix_vocab_aliases_alias'), 'vocab_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_vocab_aliases_company_id'), 'vocab_aliases', ['company_id'], unique=False)
    op.create_index(op.f('ix_vocab_aliases_id'), 'vocab_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_vocab_aliases_model'), 'vocab_aliases', ['model'], unique=False)
    op.create_table('vocab_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('search_key', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('record_data', sa.JSON(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_cache_company_id'), 'vocab_cache', ['company_id'], unique=False)
    op.create_index(op.f('ix_vocab_cache_id'), 'vocab_cache', ['id'], unique=False)
    op.create_index('ix_vocab_cache_lookup', 'vocab_cache', ['model', 'search_key', 'company_id'], unique=True)
    op.create_index(op.f('ix_vocab_cache_model'), 'vocab_cache', ['model'], unique=False)
    op.create_index(op.f('ix_vocab_cache_search_key'), 'vocab_cache', ['search_key'], unique=False)
    op.create_table('vocab_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('default_policy', sa.String(), nullable=False),
    sa.Column('company_overrides', sa.JSON(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_policies_company_id'), 'vocab_policies', ['company_id'], unique=False)
    op.create_index(op.f('ix_vocab_policies_id'), 'vocab_policies', ['id'], unique=False)
    op.create_index(op.f('ix_vocab_policies_model'), 'vocab_policies', ['model'], unique=False)
    op.create_index('ix_vocab_policy_model_company', 'vocab_policies', ['model', 'company_id'], unique=True)
    op.create_index(op.f('ix_exceptions_id'), 'exceptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_id'), table_name='exceptions')
    op.drop_index('ix_vocab_policy_model_company', table_name='vocab_policies')
    op.drop_index(op.f('ix_vocab_policies_model'), table_name='vocab_policies')
    op.drop_index(op.f('ix_vocab_policies_id'), table_name='vocab_policies')
    op.drop_index(op.f('ix_vocab_policies_company_id'), table_name='vocab_policies')
    op.drop_table('vocab_policies')
    op.drop_index(op.f('ix_vocab_cache_search_key'), table_name='vocab_cache')
    op.drop_index(op.f('ix_vocab_cache_model'), table_name='vocab_cache')
    op.drop_index('ix_vocab_cache_lookup', table_name='vocab_cache')
    op.drop_index(op.f('ix_vocab_cache_id'), table_name='vocab_cache')
    op.drop_index(op.f('ix_vocab_cache_company_id'), table_name='vocab_cache')
    op.drop_table('vocab_cache')
    op.drop_index(op.f('ix_vocab_aliases_model'), table_name='vocab_aliases')
    op.drop_index(op.f('ix_vocab_aliases_id'), table_name='vocab_aliases')
    op.drop_index(op.f('ix_vocab_aliases_company_id'), table_name='vocab_aliases')
    op.drop_index(op.f('ix_vocab_aliases_alias'), table_name='vocab_aliases')
    op.drop_index('ix_vocab_alias_lookup', table_name='vocab_aliases')
    op.drop_table('vocab_aliases')
    # ### end Alembic commands ###
