"""add_enhanced_fields_to_keymap

Revision ID: 5a5d45c79acc
Revises: 9dc2e307bf83
Create Date: 2025-10-25 01:03:17.164844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5d45c79acc'
down_revision: Union[str, None] = '9dc2e307bf83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keymaps', sa.Column('natural_key_hash', sa.String(), nullable=True))
    op.add_column('keymaps', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('keymaps', sa.Column('match_confidence', sa.Float(), nullable=True))
    op.add_column('keymaps', sa.Column('match_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keymaps', 'match_method')
    op.drop_column('keymaps', 'match_confidence')
    op.drop_column('keymaps', 'content_hash')
    op.drop_column('keymaps', 'natural_key_hash')
    # ### end Alembic commands ###
