"""add_import_ledger_tables

Revision ID: 83f79d2102e8
Revises: fcd5edb73bc7
Create Date: 2025-10-24 18:10:22.636636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f79d2102e8'
down_revision: Union[str, None] = 'fcd5edb73bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_table', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('src_hash', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('odoo_model', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('resolution_action', sa.String(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('decision_log', sa.JSON(), nullable=True),
    sa.Column('fk_map_version', sa.String(), nullable=True),
    sa.Column('quarantine_reason', sa.String(), nullable=True),
    sa.Column('quarantine_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('quarantine_resolved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_content', 'import_ledger', ['odoo_model', 'content_hash'], unique=False)
    op.create_index('idx_ledger_external_id', 'import_ledger', ['external_id'], unique=False)
    op.create_index('idx_ledger_natural_key', 'import_ledger', ['odoo_model', 'natural_key_hash'], unique=False)
    op.create_index('idx_ledger_odoo', 'import_ledger', ['odoo_model', 'odoo_id'], unique=False)
    op.create_index('idx_ledger_quarantine', 'import_ledger', ['resolution_action', 'quarantine_resolved_at'], unique=False)
    op.create_index('idx_ledger_run_batch', 'import_ledger', ['run_id', 'batch_id'], unique=False)
    op.create_index('idx_ledger_source', 'import_ledger', ['src_system', 'src_table', 'src_pk'], unique=False)
    op.create_index(op.f('ix_import_ledger_id'), 'import_ledger', ['id'], unique=False)
    op.create_table('import_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('source_data', sa.JSON(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('selected_candidate_id', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['import_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_decided_by', 'import_decisions', ['decided_by'], unique=False)
    op.create_index('idx_decision_ledger', 'import_decisions', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_import_decisions_id'), 'import_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_decisions_id'), table_name='import_decisions')
    op.drop_index('idx_decision_ledger', table_name='import_decisions')
    op.drop_index('idx_decision_decided_by', table_name='import_decisions')
    op.drop_table('import_decisions')
    op.drop_index(op.f('ix_import_ledger_id'), table_name='import_ledger')
    op.drop_index('idx_ledger_source', table_name='import_ledger')
    op.drop_index('idx_ledger_run_batch', table_name='import_ledger')
    op.drop_index('idx_ledger_quarantine', table_name='import_ledger')
    op.drop_index('idx_ledger_odoo', table_name='import_ledger')
    op.drop_index('idx_ledger_natural_key', table_name='import_ledger')
    op.drop_index('idx_ledger_external_id', table_name='import_ledger')
    op.drop_index('idx_ledger_content', table_name='import_ledger')
    op.drop_table('import_ledger')
    # ### end Alembic commands ###
