"""add_match_method_to_mapping

Revision ID: 9dc2e307bf83
Revises: ebbbff79c085
Create Date: 2025-10-25 00:59:53.513870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc2e307bf83'
down_revision: Union[str, None] = 'ebbbff79c085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('match_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mappings', 'match_method')
    # ### end Alembic commands ###
