"""add_canonical_schema_tables

Revision ID: dac0ae457af7
Revises: 83f79d2102e8
Create Date: 2025-10-24 18:13:34.628019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac0ae457af7'
down_revision: Union[str, None] = '83f79d2102e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_activity_type',
    sa.Column('activity_type_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('activity_type_sk'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_company',
    sa.Column('company_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_sk'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_lost_reason',
    sa.Column('lost_reason_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('lost_reason_sk'),
    sa.UniqueConstraint('natural_key_hash'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_product',
    sa.Column('product_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('default_code', sa.String(), nullable=True),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_template_id', sa.Integer(), nullable=True),
    sa.Column('odoo_product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('list_price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('product_sk'),
    sa.UniqueConstraint('natural_key_hash')
    )
    op.create_table('dim_stage',
    sa.Column('stage_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('fold', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('stage_sk'),
    sa.UniqueConstraint('natural_key_hash'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_utm_campaign',
    sa.Column('utm_campaign_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('utm_campaign_sk'),
    sa.UniqueConstraint('natural_key_hash'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_utm_medium',
    sa.Column('utm_medium_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('utm_medium_sk'),
    sa.UniqueConstraint('natural_key_hash'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_utm_source',
    sa.Column('utm_source_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('utm_source_sk'),
    sa.UniqueConstraint('natural_key_hash'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_partner',
    sa.Column('partner_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_table', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('src_hash', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=False),
    sa.Column('parent_sk', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vat', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('street2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('company_sk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.CheckConstraint('(is_company = 1) OR (parent_sk IS NOT NULL)', name='check_contact_has_parent'),
    sa.ForeignKeyConstraint(['company_sk'], ['dim_company.company_sk'], ),
    sa.ForeignKeyConstraint(['parent_sk'], ['dim_partner.partner_sk'], ),
    sa.PrimaryKeyConstraint('partner_sk'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('natural_key_hash')
    )
    op.create_index('idx_dim_partner_external_id', 'dim_partner', ['external_id'], unique=False)
    op.create_index('idx_dim_partner_natural_key', 'dim_partner', ['natural_key_hash'], unique=False)
    op.create_index('idx_dim_partner_odoo_id', 'dim_partner', ['odoo_id'], unique=False)
    op.create_table('dim_partner_category',
    sa.Column('category_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('company_sk', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_sk'], ['dim_company.company_sk'], ),
    sa.PrimaryKeyConstraint('category_sk'),
    sa.UniqueConstraint('natural_key_hash'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('dim_tag',
    sa.Column('tag_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('company_sk', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_sk'], ['dim_company.company_sk'], ),
    sa.PrimaryKeyConstraint('tag_sk'),
    sa.UniqueConstraint('natural_key_hash'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('bridge_partner_contact',
    sa.Column('company_sk', sa.Integer(), nullable=False),
    sa.Column('person_sk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.CheckConstraint('company_sk != person_sk', name='check_different_partners'),
    sa.ForeignKeyConstraint(['company_sk'], ['dim_partner.partner_sk'], ),
    sa.ForeignKeyConstraint(['person_sk'], ['dim_partner.partner_sk'], ),
    sa.PrimaryKeyConstraint('company_sk', 'person_sk')
    )
    op.create_table('bridge_tags_partner',
    sa.Column('partner_sk', sa.Integer(), nullable=False),
    sa.Column('tag_sk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_sk'], ['dim_partner.partner_sk'], ),
    sa.ForeignKeyConstraint(['tag_sk'], ['dim_partner_category.category_sk'], ),
    sa.PrimaryKeyConstraint('partner_sk', 'tag_sk')
    )
    op.create_table('dim_user',
    sa.Column('user_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('partner_sk', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_sk'], ['dim_partner.partner_sk'], ),
    sa.PrimaryKeyConstraint('user_sk'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('fact_message',
    sa.Column('message_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('anchor_model', sa.String(), nullable=False),
    sa.Column('anchor_sk', sa.Integer(), nullable=False),
    sa.Column('author_sk', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.CheckConstraint("anchor_model IN ('fact_lead', 'dim_partner')", name='check_message_anchor_model'),
    sa.ForeignKeyConstraint(['author_sk'], ['dim_partner.partner_sk'], ),
    sa.PrimaryKeyConstraint('message_sk'),
    sa.UniqueConstraint('natural_key_hash')
    )
    op.create_table('fact_activity',
    sa.Column('activity_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_table', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('src_hash', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('anchor_model', sa.String(), nullable=False),
    sa.Column('anchor_sk', sa.Integer(), nullable=False),
    sa.Column('user_sk', sa.Integer(), nullable=False),
    sa.Column('activity_type_sk', sa.Integer(), nullable=False),
    sa.Column('date_deadline', sa.Date(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.CheckConstraint("anchor_model IN ('fact_lead', 'dim_partner')", name='check_activity_anchor_model'),
    sa.ForeignKeyConstraint(['activity_type_sk'], ['dim_activity_type.activity_type_sk'], ),
    sa.ForeignKeyConstraint(['user_sk'], ['dim_user.user_sk'], ),
    sa.PrimaryKeyConstraint('activity_sk'),
    sa.UniqueConstraint('natural_key_hash')
    )
    op.create_index('idx_fact_activity_anchor', 'fact_activity', ['anchor_model', 'anchor_sk'], unique=False)
    op.create_table('fact_lead',
    sa.Column('lead_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_table', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('src_hash', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('partner_sk', sa.Integer(), nullable=True),
    sa.Column('user_sk', sa.Integer(), nullable=False),
    sa.Column('stage_sk', sa.Integer(), nullable=False),
    sa.Column('lost_reason_sk', sa.Integer(), nullable=True),
    sa.Column('utm_source_sk', sa.Integer(), nullable=True),
    sa.Column('utm_medium_sk', sa.Integer(), nullable=True),
    sa.Column('utm_campaign_sk', sa.Integer(), nullable=True),
    sa.Column('company_sk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('email_from', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('expected_revenue', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('probability', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('date_open', sa.DateTime(), nullable=True),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_sk'], ['dim_company.company_sk'], ),
    sa.ForeignKeyConstraint(['lost_reason_sk'], ['dim_lost_reason.lost_reason_sk'], ),
    sa.ForeignKeyConstraint(['partner_sk'], ['dim_partner.partner_sk'], ),
    sa.ForeignKeyConstraint(['stage_sk'], ['dim_stage.stage_sk'], ),
    sa.ForeignKeyConstraint(['user_sk'], ['dim_user.user_sk'], ),
    sa.ForeignKeyConstraint(['utm_campaign_sk'], ['dim_utm_campaign.utm_campaign_sk'], ),
    sa.ForeignKeyConstraint(['utm_medium_sk'], ['dim_utm_medium.utm_medium_sk'], ),
    sa.ForeignKeyConstraint(['utm_source_sk'], ['dim_utm_source.utm_source_sk'], ),
    sa.PrimaryKeyConstraint('lead_sk'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('natural_key_hash')
    )
    op.create_index('idx_fact_lead_content_hash', 'fact_lead', ['content_hash'], unique=False)
    op.create_index('idx_fact_lead_natural_key', 'fact_lead', ['natural_key_hash'], unique=False)
    op.create_index('idx_fact_lead_odoo_id', 'fact_lead', ['odoo_id'], unique=False)
    op.create_index('idx_fact_lead_partner_sk', 'fact_lead', ['partner_sk'], unique=False)
    op.create_table('fact_order',
    sa.Column('order_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('src_hash', sa.String(), nullable=False),
    sa.Column('natural_key_hash', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('partner_sk', sa.Integer(), nullable=False),
    sa.Column('user_sk', sa.Integer(), nullable=False),
    sa.Column('company_sk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_order', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('amount_total', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_sk'], ['dim_company.company_sk'], ),
    sa.ForeignKeyConstraint(['partner_sk'], ['dim_partner.partner_sk'], ),
    sa.ForeignKeyConstraint(['user_sk'], ['dim_user.user_sk'], ),
    sa.PrimaryKeyConstraint('order_sk'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('natural_key_hash')
    )
    op.create_table('bridge_tags_lead',
    sa.Column('lead_sk', sa.Integer(), nullable=False),
    sa.Column('tag_sk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lead_sk'], ['fact_lead.lead_sk'], ),
    sa.ForeignKeyConstraint(['tag_sk'], ['dim_tag.tag_sk'], ),
    sa.PrimaryKeyConstraint('lead_sk', 'tag_sk')
    )
    op.create_table('fact_order_line',
    sa.Column('line_sk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_system', sa.String(), nullable=False),
    sa.Column('src_pk', sa.String(), nullable=False),
    sa.Column('order_sk', sa.Integer(), nullable=False),
    sa.Column('product_sk', sa.Integer(), nullable=False),
    sa.Column('product_uom_qty', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('price_unit', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_sk'], ['fact_order.order_sk'], ),
    sa.ForeignKeyConstraint(['product_sk'], ['dim_product.product_sk'], ),
    sa.PrimaryKeyConstraint('line_sk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_order_line')
    op.drop_table('bridge_tags_lead')
    op.drop_table('fact_order')
    op.drop_index('idx_fact_lead_partner_sk', table_name='fact_lead')
    op.drop_index('idx_fact_lead_odoo_id', table_name='fact_lead')
    op.drop_index('idx_fact_lead_natural_key', table_name='fact_lead')
    op.drop_index('idx_fact_lead_content_hash', table_name='fact_lead')
    op.drop_table('fact_lead')
    op.drop_index('idx_fact_activity_anchor', table_name='fact_activity')
    op.drop_table('fact_activity')
    op.drop_table('fact_message')
    op.drop_table('dim_user')
    op.drop_table('bridge_tags_partner')
    op.drop_table('bridge_partner_contact')
    op.drop_table('dim_tag')
    op.drop_table('dim_partner_category')
    op.drop_index('idx_dim_partner_odoo_id', table_name='dim_partner')
    op.drop_index('idx_dim_partner_natural_key', table_name='dim_partner')
    op.drop_index('idx_dim_partner_external_id', table_name='dim_partner')
    op.drop_table('dim_partner')
    op.drop_table('dim_utm_source')
    op.drop_table('dim_utm_medium')
    op.drop_table('dim_utm_campaign')
    op.drop_table('dim_stage')
    op.drop_table('dim_product')
    op.drop_table('dim_lost_reason')
    op.drop_table('dim_company')
    op.drop_table('dim_activity_type')
    # ### end Alembic commands ###
