"""add_detection_fields_to_column_profile

Revision ID: ebbbff79c085
Revises: dac0ae457af7
Create Date: 2025-10-25 00:57:55.629831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbbff79c085'
down_revision: Union[str, None] = 'dac0ae457af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_profiles', sa.Column('detected_entity', sa.JSON(), nullable=True))
    op.add_column('column_profiles', sa.Column('polymorphic_signature', sa.JSON(), nullable=True))
    op.add_column('column_profiles', sa.Column('pivot_group', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_profiles', 'pivot_group')
    op.drop_column('column_profiles', 'polymorphic_signature')
    op.drop_column('column_profiles', 'detected_entity')
    # ### end Alembic commands ###
